const aboutTeamData = [
  {
    img: "/about/PranaySharma.png",
    name: "Pranay Sharma",
    role: "Lead Hardware Design Engineer & EMI/EMC Expert",
    desc: "A Hardware Design Engineer and Project Lead with over 5+ years of expertise, he has successfully contributed to the development of more than 300 products.",
    social: " https://www.linkedin.com/in/pranay-sharma-223747175/ ",
    contact: "pranay@ubyte.in",
  },
  {
    img: "/about/LalitMohan.jpg",
    name: "Lalit Mohan",
    role: "CFO | Accounts Manager",
    desc: " With over 26 years of experience in accounting and financial management, he specializes in finalizing accounts.",
    social: "https://www.linkedin.com/in/lalit-mohan-41aa26201/ ",
    contact: "lalit.sharma@ubyte.in",
  },
  {
    img: "/about/AshaSharma.png",
    name: "Asha Sharma",
    role: "CEO | Customer Relationship Manager",
    desc: "Expertise in customer relationship management and ensuring seamless project execution and timely delivery to clients.",
    social: "https://www.linkedin.com/in/asha-sharma-88b94b33a/ ",
    contact: " asha@ubyte.in",
  },
  {
    img: "/about/Shivansh.jpg",
    name: "Shivansh Chauhan",
    role: "Lead Full Stack & Embedded Developer",
    desc: "A skilled Full Stack Developer with 2+ years of experience specializing in the MERN stack. He has successfully delivered 10+ projects to clients.",
    social: "https://www.linkedin.com/in/shivansh-chauhan-3770r/ ",
    contact: "shivansh@ubyte.in",
  },
  {
    img: "/about/DhanveerKalsi.jpg",
    name: "Dhanveer Singh",
    role: "Lead Firmware & Automotive Software Developer ",
    desc: "A highly Skilled Embedded Firmware Developer with 4+ years of experience in prouct development and 20+ products.",
    social: "https://www.linkedin.com/in/dhanveerkalsi/ ",
    contact: "dhanveer.kalsi@ubyte.in",
  },
  {
    img: "/about/Rohit.jpg",
    name: "Rohit Maurya",
    role: "Full Stack & React Native Developer",
    desc: "A full Stack Developer with 2+ years of experience specializing in the MERN stack. He has delivered 8+ projects, including 2 React and React Native products.",
    social: "https://www.linkedin.com/in/rohit-maurya-3b7a43214/",
    contact: "rohit@ubyte.in",
  },
  {
    img: "/about/LakshyaSharma.jpg",
    name: "Lakshay Sharma",
    role: "Hardware Design Engineer",
    desc: "A Hardware Design Engineer with a passion for building and experimenting with electronics. I love turning concepts into functional designs, constantly learning, and solving challenges along the way.",
    social: "https://www.linkedin.com/in/lakshya-sharma-907513326",
    contact: "lakshya.sharma@ubyte.in",
  },
  {
    img: "/about/HimanshuChandel.JPG",
    name: " Himanshu Chandel",
    role: "Hardware Design Engineer",
    desc: "A Hardware Design Engineer who loves bringing ideas to life through circuits and embedded systems. Passionate about problem-solving, innovation and developing hardware that makes a real impact",
    social: "https://www.linkedin.com/in/himanshu-chandel-015287235/ ",
    contact: "himanshu.chandel@ubyte.in",
  },
];

export default aboutTeamData;
